version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    assignees: [skilbjo]
    rebase-strategy: auto
    versioning-strategy: increase
    open-pull-requests-limit: 3
    commit-message:
      prefix: fix
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    assignees: [skilbjo]
    open-pull-requests-limit: 1
    commit-message:
      prefix: fix
      include: scope
