name: pr

on:
  pull_request_target: # https://github.com/dependabot/dependabot-core/issues/3253
    branches: [ master ]

defaults:
  run:
    shell: bash
    working-directory: ./sdk-example

permissions:
  pull-requests: write
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          token: ${{ secrets.ACTIONS_TOKEN }} # replace w/ secrets.GITHUB_TOKEN when repo made public
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v3
        with:
          node-version-file: sdk-example/.nvmrc
          cache: npm
          cache-dependency-path: sdk-example/package-lock.json

      - run: make ci

      - uses: cycjimmy/semantic-release-action@v2.7.0
        with:
          working_directory: ./sdk-example
          semantic_version: 17
          extra_plugins: |
            @semantic-release/exec@6.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }} # replace w/ secrets.GITHUB_TOKEN when repo made public

  dependabot-approve-and-automerge:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: dependabot/fetch-metadata@v1.2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
