name: release

on:
  push:
    branches: [ master ]

defaults:
  run:
    shell: bash
    working-directory: ./sdk-example

jobs:
  publish-artifact:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_TOKEN }} # replace w/ secrets.GITHUB_TOKEN when repo made public
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version-file: sdk-example/.nvmrc
          cache: npm
          cache-dependency-path: sdk-example/package-lock.json

      - uses: cycjimmy/semantic-release-action@v3.0.0
        with:
          working_directory: ./sdk-example
          semantic_version: 18
          extra_plugins: |
            @semantic-release/exec@6.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }} # replace w/ secrets.GITHUB_TOKEN when repo made public
